### ISSUE TITLE
コメントが固定的

### ISSUE THREAD

**Issue by shonsukee** [shonsukee/screpo#3]
# 課題
コメントの大きさを固定的にしている影響で画面が小さいものであれば下にスクロールする必要が出てきたり，大きければテキストボックスが小さくて見にくくなる課題がある．

# 解決策
- vw, vhを用いる
- 画面幅に応じた対応をとる

実装例
```html
    <textarea
        name="student_name1"
        id="student_name1"
        class="resize-textarea"
        placeholder="生徒1"
    ></textarea>
```

```css
.resize-textarea {
  width: 70%; /* 初期のテキストボックスの幅を設定 */
  height: 100px; /* 初期のテキストボックスの高さを設定 */
  resize: none; /* ユーザーがテキストボックスのサイズを変更できないようにする */
  transition: width 0.5s, height 0.5s; /* サイズ変更時のアニメーションを追加 */
}

/* 画面幅が 480px 以下の場合のスタイル */
@media (max-width: 480px) {
  .resize-textarea {
    width: 95vw; /* 画面幅の95%に設定 */
    height: 60px; /* 高さをさらに調整 */
  }
}
```

# 確認事項
- [ ] すでに満足しているユーザに問題が生じないか
- [ ] 小さい画面のデバイスは，スクロールしなくてもいい大きさの表示になっているか
- [ ] 大きい画面のデバイスは，テキストボックスが拡大されているか
